# Basic project details.
site_name: 'Synthetix System Documentation'
site_description: 'Decentralised Synthetic Assets'
site_author: 'Synthetix Team'
site_url: ''

# Links to the core Synthetix smart contract repository.
repo_name: 'synthetixio/synthetix'
repo_url: 'https://github.com/synthetixio/synthetix'

# Setting `edit_uri` to an empty string disables the edit button, which points to the wrong page.
# If at some point this documentation is moved into the core synthetix repository, then this can be
# removed.
edit_uri: ''

docs_dir: 'content'

# This copyright notice will be rendered in the footer.
copyright: '<a href=https://github.com/Synthetixio/synthetix/blob/master/LICENSE>Copyright &copy Synthetix 2018 - 2020</a>'

# Top level headings become tabs at the top due to `tabs: true` in the theme.
nav:
  - System Overview:
      - Home: index.md
      - Synopsis: synopsis.md
      - Incentives: incentives.md
      - Governance: governance.md
  - Litepaper:
      - Home: litepaper/index.md
      - Korean: litepaper/korean.md
      - Russian: litepaper/russian.md
      - Chinese: litepaper/chinese.md
  - Addresses:
      - '': addresses.md
  - Releases:
      - '': releases.md
  - Tokens:
      - '': tokens.md
  - Integrations:
      - Home: integrations/index.md
      - Integration Guide: integrations/guide.md
      - Working with Testnets: integrations/testnets.md
      - ENS Support: integrations/ens.md
  - Historical Data:
      - '': historical-data.md
  - Libraries:
      - Home: libraries/index.md
      - Versioning: libraries/versioning.md
      - Examples: libraries/examples.md
      - synthetix: libraries/synthetix.md
      - synthetix-js: libraries/synthetix-js.md
      - synthetix-data: libraries/synthetix-data.md
  - Smart Contracts:
      - Architecture: contracts/index.md
      - Automated Testing: contracts/testing.md
      - Publisher: contracts/publisher.md
      - Transaction Guide: contracts/transactions.md
      - Libraries:
          - Math: contracts/Math.md
          - SafeDecimalMath: contracts/SafeDecimalMath.md
          - SafeMath: contracts/SafeMath.md
      - Walkthrus:
          - Overview: contracts/walkthrus/index.md
          - Claiming Rewards: contracts/walkthrus/claiming.md
          - Delegating: contracts/walkthrus/delegating.md
          - 'Depot: ETH/sUSD': contracts/walkthrus/depot.md
          - Staking SNX: contracts/walkthrus/staking.md
          - Trading: contracts/walkthrus/trading.md
          - Trading Settlement: contracts/walkthrus/settlement.md
          - Unstaking SNX: contracts/walkthrus/unstaking.md
      - Contracts:
          - AddressResolver: contracts/AddressResolver.md
          - DelegateApprovals: contracts/DelegateApprovals.md
          - Depot: contracts/Depot.md
          - EscrowChecker: contracts/EscrowChecker.md
          - EternalStorage: contracts/EternalStorage.md
          - EtherCollateral: contracts/EtherCollateral.md
          - Exchanger: contracts/Exchanger.md
          - ExchangeRates: contracts/ExchangeRates.md
          - ExchangeState: contracts/ExchangeState.md
          - ExternStateToken: contracts/ExternStateToken.md
          - FeePool: contracts/FeePool.md
          - FeePoolEternalStorage: contracts/FeePoolEternalStorage.md
          - FeePoolState: contracts/FeePoolState.md
          - IssuanceEternalStorage: contracts/IssuanceEternalStorage.md
          - Issuer: contracts/Issuer.md
          - LimitedSetup: contracts/LimitedSetup.md
          - Migrations: contracts/Migrations.md
          - MixinResolver: contracts/MixinResolver.md
          - MultiCollateralSynth: contracts/MultiCollateralSynth.md
          - Owned: contracts/Owned.md
          - Pausable: contracts/Pausable.md
          - Proxy: contracts/Proxy.md
          - Proxyable: contracts/Proxyable.md
          - ProxyERC20: contracts/ProxyERC20.md
          - PurgeableSynth: contracts/PurgeableSynth.md
          - RewardEscrow: contracts/RewardEscrow.md
          - RewardsDistribution: contracts/RewardsDistribution.md
          - RewardsDistributionRecipient: contracts/RewardsDistributionRecipient.md
          - SelfDestructible: contracts/SelfDestructible.md
          - State: contracts/State.md
          - SupplySchedule: contracts/SupplySchedule.md
          - Synth: contracts/Synth.md
          - Synthetix: contracts/Synthetix.md
          - SynthetixEscrow: contracts/SynthetixEscrow.md
          - SynthetixState: contracts/SynthetixState.md
          - SystemStatus: contracts/SystemStatus.md
          - TokenState: contracts/TokenState.md
      - Audit History: contracts/audits.md

# These social links will be rendered as icons in the footer, as long as the type corresponds to FontAwesome glyph.
extra:
  social:
    - icon: 'brands/github'
      link: 'https://github.com/synthetixio'
    - icon: 'brands/twitter'
      link: 'https://twitter.com/synthetix_io'
    - icon: 'brands/discord'
      link: 'https://discordapp.com/channels/413890591840272394/'
    - icon: 'brands/reddit'
      link: 'https://www.reddit.com/r/synthetix_io/'
    - icon: 'brands/medium'
      link: 'https://blog.synthetix.io'

# This set of documentation uses the MkDocs Material theme by squidfunk: https://github.com/squidfunk/mkdocs-material
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'black'
    accent: 'indigo'
  logo: 'img/logos/synthetix_logo.svg'
  favicon: 'img/favicon.ico'
  feature:
    tabs: true
    instant: false

# Extension settings.
# In addition to the standard extensions, this also requires the PyMdown Extensions by facelessuser: https://github.com/facelessuser/pymdown-extensions
markdown_extensions:
  - toc:
      permalink: True # Generates permanent links for each page section.
  - admonition # Small descriptive elements for notes, warnings, etc.
  - pymdownx.arithmatex # Math rendering.
  - pymdownx.tasklist: # Allows nested and better checkboxes.
      custom_checkbox: True # Without this setting, checkboxes look rubbish in the material theme.
  - pymdownx.highlight: # Code syntax highlighting.
      linenums: True
  - pymdownx.extra: # Better fenced code blocks, emphasis, footnotes, lists, tables, abbreviations, and raw HTML.
      pymdownx.betterem:
        smart_enable: 'all' # Smarter line breaks when emphasising lines.
  - pymdownx.details # Collapsible admonition-style blocks containing further information.
  - pymdownx.escapeall # Backslashes escape everything.
  - pymdownx.caret # Superscripts and insert text.
  - pymdownx.superfences
  - pymdownx.tabbed # tabs
  - pymdownx.tilde # Strikethrough and underlines.
  - pymdownx.magiclink: # Better links and github references.
      provider: 'github'
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      user: 'synthetixio'
      repo: 'synthetix'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'js/sectionSeparators.js'

extra_css: [extra.css]
